app:
    build: .
    expose:
        - "5000"

nginx:
    image: nginx
    ports:
        - "1337:80"
    volumes:
        - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
        - app

